# Generated by Django 5.1.4 on 2025-01-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paragraphe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('ordre', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('position', models.CharField(choices=[('Gauche', 'Gauche'), ('Milieu', 'Milieu'), ('Droite', 'Droite')], default='Gauche', max_length=6)),
                ('ligne', models.CharField(choices=[('Une', 'Une'), ('Deux', 'Deux'), ('Trois', 'Trois'), ('Quatre', 'Quatre'), ('Cinq', 'Cinq'), ('Six', 'Six'), ('Sept', 'Sept'), ('Huit', 'Huit'), ('Neuf', 'Neuf'), ('Dix', 'Dix')], default='Une', max_length=6)),
                ('largeur', models.CharField(choices=[('Classique', 'Classique'), ('Large', 'Large'), ('Xlarge', 'Extra Large')], default='Classique', max_length=11)),
                ('fond', models.CharField(choices=[('Rose', 'Rose'), ('Jaune', 'Jaune'), ('Vert', 'Vert'), ('Blanc', 'Blanc'), ('vertCanard', 'Vert canard'), ('Transparent', 'Transparent')], default='Blanc', max_length=11)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
