# Generated by Django 5.1.4 on 2025-01-31 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraphe',
            old_name='ligne',
            new_name='ordre_affichage',
        ),
    ]
