# Generated by Django 5.1.4 on 2025-02-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rename_ligne_paragraphe_ordre_affichage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paragraphe',
            options={'ordering': ['ordre_d_affichage']},
        ),
        migrations.RenameField(
            model_name='paragraphe',
            old_name='ordre_affichage',
            new_name='ordre_d_affichage',
        ),
        migrations.RenameField(
            model_name='paragraphe',
            old_name='ordre',
            new_name='ordre_dans_l_admin',
        ),
        migrations.AddField(
            model_name='paragraphe',
            name='titre_affiché_dans_le_menu',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Oui', max_length=4),
        ),
    ]
