# Generated by Django 5.1.1 on 2025-03-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_paragraphe_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paragraphe',
            options={'ordering': ['ordre_dans_l_admin']},
        ),
        migrations.AlterField(
            model_name='paragraphe',
            name='titre_affiché_dans_le_menu',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], default='Oui', max_length=4),
        ),
    ]
